on: [push]

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  package:
    runs-on: ubuntu-latest
    container:
      image: wonderlandengine/editor:latest
    steps:
    - uses: actions/checkout@v2
    - name: Package
      run: /usr/local/bin/entrypoint.sh WonderlandEditor --windowless --package --project ./MouseDefense.wlp --output public
      env:
          WLE_CREDENTIALS: ${{ secrets.WLE_CREDENTIALS }}
    - name: Gzip
      run: gzip -k deploy/**/*.*
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./public
    - name: Upload package artifact
      uses: actions/upload-artifact@v2
      with:
        name: mouse-defense-deploy
        path: public/

  deploy-heyvr:
    needs: package
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/')
    container:
      image: node:18-alpine
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Download package artifact
      uses: actions/download-artifact@v2
      with:
        name: mouse-defense-deploy
        path: public/
    - name: Install script dependencies
      run: cd scripts && npm ci
    - name: Run publish script
      run: cd scripts && npm run publish:heyvr -- ${{ github.ref_name }}
      env:
        HEYVR_ACCESS_TOKEN: ${{ secrets.HEYVR_ACCESS_TOKEN }}

  deploy-pages:
    needs: package
    runs-on: ubuntu-latest
    if: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
